---
- name: Create tower Credential
  tower_credential:
    name: "{{ item.tower_credential_name }}"
    authorize: "{{ item.tower_credential_authorize | default(tower_credential_authorize)  }}"
    authorize_password: "{{ item.tower_credential_autorize_password | default(tower_credential_autorize_password) }}"
    become_method: "{{ item.tower_credential_become_method | default(tower_credential_become_method) }}"
    become_password: "{{ item.tower_credential_become_password | default(tower_credential_become_password) }}"
    client: "{{ item.tower_credential_client | default(tower_credential_client)}}"
    description: "{{ item.tower_credential_description | default(tower_credential_description) }}"
    domain: "{{ item.tower_credential_domain | default(tower_credential_domain) }}"
    host: "{{ item.tower_credential_host | default(tower_credential_host) }}"
    kind: "{{ item.tower_credential_kind | default(tower_credential_kind) }}"
    organization: "{{ item.tower_credential_organization | default(tower_credential_organization)}}"
    password: "{{ item.tower_credential_password | default(tower_credential_password) }}"
    project: "{{ item.tower_credential_project | default(tower_credential_project) }}"
    secret: "{{ item.tower_credential_secret | default(tower_credential_secret) }}"
    ssh_key_data: "{{ item.tower_credential_ssh_key_data | default(tower_credential_ssh_key_data) }}"
    ssh_key_unlock: "{{ item.tower_credential_ssh_key_unlock | default(tower_credential_ssh_key_unlock) }}"
    state: "{{ item.tower_credential_state | default(tower_credential_state) }}"
    subscription: "{{ item.tower_credential_subscription | default(tower_credential_subscription) }}"
    # team: "{{ item.tower_credential_team | default(tower_credential_team) }}"
    tenant: "{{ item.tower_credential_tenant | default(tower_credential_tenant) }}"
    tower_config_file: "{{ item.tower_credential_tower_config_file | default(tower_credential_tower_config_file) }}"
    tower_host: "{{ tower_host_name }}"
    tower_username: "{{ tower_toweradmin_user_name }}"
    tower_password: "{{ tower_toweradmin_user_password }}"
    tower_verify_ssl: "{{ item.tower_credential_tower_verify_ssl | default(tower_credential_tower_verify_ssl) }}"
    # user: "{{ item.tower_credential_user | default(tower_credential_user) }}"
    username: "{{ item.tower_credential_username | default(tower_credential_username) }}"
    vault_password: "{{ item.tower_credential_vault_password | default(tower_credential_vault_password) }}"
  with_items: "{{ tower_credentials }}"
