---
- name: Create tower Job Template
  tower_job_template:
    name: "{{ item.tower_job_template_name }}"
    ask_credential: "{{ item.tower_job_template_ask_credential | default(tower_job_template_ask_credential)  }}"
    ask_extra_vars: "{{ item.tower_job_template_ask_extra_vars | default(tower_job_template_ask_extra_vars) }}"
    ask_inventory: "{{ item.tower_job_template_ask_inventory | default(tower_job_template_ask_inventory) }}"
    ask_job_type: "{{ item.tower_job_template_ask_job_type | default(tower_job_template_ask_job_type) }}"
    ask_tags: "{{ item.tower_job_template_ask_tags | default(tower_job_template_ask_tags)}}"
    become_enabled: "{{ item.tower_job_template_become_enabled | default(tower_job_template_become_enabled) }}"
    cloud_credential: "{{ item.tower_job_template_cloud_credential | default(tower_job_template_cloud_credential) }}"
    description: "{{ item.tower_job_template_description | default(tower_job_template_description) }}"
    # extra_vars_path: "{{ item.tower_job_template_extra_vars_path | default(tower_job_template_extra_vars_path) }}"
    forks: "{{ item.tower_job_template_forks | default(tower_job_template_forks)}}"
    host_config_key: "{{ item.tower_job_template_host_config_key | default(tower_job_template_host_config_key) }}"
    inventory: "{{ item.tower_job_template_inventory | default(tower_job_template_inventory) }}"
    job_tags: "{{ item.tower_job_template_job_tags | default(tower_job_template_job_tags) }}"
    job_type: "{{ item.tower_job_template_job_type | default(tower_job_template_job_type) }}"
    limit: "{{ item.tower_job_template_limit | default(tower_job_template_limit) }}"
    machine_credential: "{{ item.tower_job_template_machine_credential | default(tower_job_template_machine_credential) }}"
    network_credential: "{{ item.tower_job_template_network_credential | default(tower_job_template_network_credential) }}"
    playbook: "{{ item.tower_job_template_playbook | default(tower_job_template_playbook) }}"
    project: "{{ item.tower_job_template_project | default(tower_job_template_project) }}"
    skip_tags: "{{ item.tower_job_template_skip_tags | default(tower_job_template_skip_tags) }}"
    state: "{{ item.tower_job_template_state | default(tower_job_template_state) }}"
    tower_config_file: "{{ item.tower_job_template_tower_config_file | default(tower_job_template_tower_config_file) }}"
    tower_host: "{{ tower_host_name }}"
    tower_username: "{{ tower_toweradmin_user_name }}"
    tower_password: "{{ tower_toweradmin_user_password }}"
    tower_verify_ssl: "{{ item.tower_job_template_tower_verify_ssl | default(tower_job_template_tower_verify_ssl) }}"
    # verbosity: "{{ item.tower_job_template_verbosity | default(tower_job_template_verbosity) }}"
  with_items: "{{ tower_job_templates }}"
